### ISSUE TITLE
若需要在fragment.vue中点击切换当前fragment该如何处理呢

### ISSUE THREAD

**Issue by Mrxyx** [hanliuxin5/ControllerView#3]
你好  感谢开源项目带来的灵感， 若需要在fragment1.vue中触发切换当前fragment
例如fragment1.vue中包含一个列表页，点击列表页需要将当前fragment切换到详情页（只切换当前fragment,tabbar不改变），有没有好的方法？
暂时的想法是定义module  module中调用ControllerViewActivity中的renderChange方法？

**Comment by hanliuxin5** [comment]
我觉得比较好的办法其实是顺着android里的思路，用` getFragmentManager()`来操作当前`activity`的页面逻辑，而对于fragment里的页面逻辑则继续使用`getChildFragmentManager()`来完成嵌套页面的逻辑。
还有一点就是你的renderChange我不知道会怎么来实现，不好评价。

**Comment by Mrxyx** [comment]
可能你误解我的意思了  不是说在fragment中嵌套fragment， 而是将当前列表页fragment用另一个详情页fragment替换掉。
renderChange方法就是代码中ControllerViewActivity类的onControllerChanged方法😅。其实就是修改src的值来改变fragment?

**Comment by hanliuxin5** [comment]
哦哦，那就可以在这个基础上定义一个切换事件，将fragmentmanager的`replace`暴露出来给前端页面调用。

**Comment by Mrxyx** [comment]
💓  thx   多谢解答  不过我现在放弃了  决定用单页面来做（部分布局切换）啦   boss要求尽量的不要依赖原生  要考虑ios😷。。。  再次感谢 👍
